# Generated by Django 5.2.4 on 2025-12-12 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codPostal', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('idMaquina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField(unique=True)),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='first.ciudad')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='first.proveedor')),
                ('usuarioEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='first.usuario')),
            ],
            options={
                'ordering': ['-fechaHora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='first.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='first.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RecargaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='first.ciudad')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='first.maquina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='first.producto')),
                ('usuarioResponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas_realizadas', to='first.usuario')),
            ],
            options={
                'ordering': ['-fechaHora'],
            },
        ),
        migrations.CreateModel(
            name='StockCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadDisponible', models.IntegerField(default=0)),
                ('estado_alerta', models.BooleanField(default=False)),
                ('umbral_alerta', models.IntegerField(default=15)),
                ('fecha_ultima_alerta', models.DateTimeField(blank=True, null=True)),
                ('mensaje_alerta', models.TextField(blank=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.ciudad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.producto')),
            ],
            options={
                'unique_together': {('producto', 'ciudad')},
            },
        ),
    ]
