# Generated by Django 5.2.4 on 2025-08-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_ciudad_compra_detallecompra_maquina_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='subtotal',
        ),
    ]
