# Generated by Django 5.2.4 on 2025-08-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_detallecompra_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='first.maquina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='first.producto')),
                ('usuarioResponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas_realizadas', to='first.usuario')),
            ],
            options={
                'ordering': ['-fechaHora'],
            },
        ),
    ]
