# Generated by Django 5.2.4 on 2025-08-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_recargamaquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
