# Generated by Django 5.2.4 on 2025-08-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first", "0006_usuario_is_active_usuario_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="recargamaquina",
            name="ciudad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recargas",
                to="first.ciudad",
            ),
        ),
        migrations.CreateModel(
            name="StockCiudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidadDisponible", models.IntegerField(default=0)),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_por_producto",
                        to="first.ciudad",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_por_ciudad",
                        to="first.producto",
                    ),
                ),
            ],
            options={
                "unique_together": {("producto", "ciudad")},
            },
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
