# Generated by Django 5.2.4 on 2025-09-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_recargamaquina_ciudad_stockciudad_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockciudad',
            name='estado_alerta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockciudad',
            name='fecha_ultima_alerta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockciudad',
            name='mensaje_alerta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockciudad',
            name='umbral_alerta',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='stockciudad',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.ciudad'),
        ),
        migrations.AlterField(
            model_name='stockciudad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.producto'),
        ),
    ]
